# Generated by Django 5.0.6 on 2024-11-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureFiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=150)),
                ('publish_date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('total_pages', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='static/uploads')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassicBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=150)),
                ('publish_date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('total_pages', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='static/uploads')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RomanceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=150)),
                ('publish_date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('total_pages', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='static/uploads')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThrillersBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=150)),
                ('publish_date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('total_pages', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='static/uploads')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reviews', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
